name: Metrics
on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: luxass
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Copenhagen
          config_twemoji: yes
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # repositories_skipped:
          use_prebuilt_image: yes
